import Header from "@/components/layouts/Header";
import { geistMono, geistSans } from "@/types/font";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Nic App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
